# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'readenjoy' do
	
  pod 'ZXingObjC', '~> 3.0'

  pod 'LBXAlertAction'

  pod 'ZYCornerRadius', git:'https://github.com/liuzhiyi1992/ZYCornerRadius.git',tag:'0.9.1'

end

